### ISSUE TITLE
Releases and Docker Images

### ISSUE THREAD

**Issue by wi1dcard** [Elepover/pmcenter#19]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could have releases, pre-built binaries and docker images for pmcenter.

**Describe the solution you'd like**
Setting up a CI/CD pipeline would be a pretty good solution I think.

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by Elepover** [comment]
Thanks for the feedback! Sorry for the late response but I'll soon start working on it.

**Comment by Elepover** [comment]
I've created a [docker hub repository](https://hub.docker.com/repository/docker/elep0ver/pmcenter/) with docker image pre-built available, and updated the [README file](https://github.com/Elepover/pmcenter#use-docker), which you can check out right now.

Since pmcenter has its own updates system, currently I'm not going for the CI/CD pipeline solution (although it's considered pretty awesome).

Closing this issue, feel free to open it again for additional info.
